[workspace]
members = ["programs/*"]

[toolchain]


[features]
seeds = false
skip-lint = false

[programs.devnet]
create_token = "5VebaeFAsUx3xWjngDkvoJKCDVUxdxVt8b7QSNnzDeTT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

